# Group Accounts


## Account List [/accounts/{?per_page,page,search,include,type,uid,start,end}]

+ Parameters

    + per_page: 20 (number, optional) - The number of results per page.
        + Default: `20`
    + page: 1 (number, optional) - The current page number of results.
        + Default: `1`
    + search (string, optional) - The search keyword.
    + include: owner (string, optional) - The additional object to be included.
    + type (string, optional) - The type of account.
    + uid (number, optional) - Filter accounts by user id.
    + start (string, optional) - The start date of filtering accounts.
    + end (string, optional) - The end date of filtering accounts.

### List All Accounts [GET]

Fetches all available accounts with pagination

+ Response 200 (application/json)
    + Body

            [
                {
                    "id": 1,
                    "account_no": 503,
                    "vendor_id": 1,
                    "vendor_name": Apple,
                    "ledger_id": "104 (Tea)",
                    "particulars": "due",
                    "account_details": [
                        {
                            "id": 1,
                            "ledger_id": 503,
                            "account_no": 503,
                            "trn_no": 504,
                            "particulars": "nothing",
                            "amount": 80,
                            "tax": 20,
                            "line_total": 100
                        },
                        {
                            "id": 2,
                            "ledger_id": 504,
                            "account_no": 503,
                            "trn_no": 504,
                            "particulars": "nothing",
                            "amount": 90,
                            "tax": 30,
                            "line_total": 120
                        },
                    ],
                    "date": "2016-11-22",
                    "due_date": "2016-11-22",
                    "subtotal": 200,
                    "total": 200,
                    "reference_no": "Account-001",
                    "created_by": {
                        "id": 1,
                        "user_nicename": "john",
                        "user_email": "mail@gmail.com",
                        "user_url": "",
                        "display_name": "John Wick",
                        "avatar": "http://2.gravatar.com/avatar/50b8fc98057e12e1f1f8982a981297e7?s=96&d=mm&r=g",
                        "_links": {
                            "self": [
                                {
                                    "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                                }
                            ],
                            "collection": [
                                {
                                    "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                                }
                            ]
                        }
                    },
                    "_links": {
                        "self": [
                            {
                                "href": "http://example.com/wp-json/erp/v1/accounting/accounts/1"
                            }
                        ],
                        "collection": [
                            {
                                "href": "http://example.com/wp-json/erp/v1/accounting/accounts"
                            }
                        ]
                    }
                }
            ]

## Account List [/accounts]

### Create A Account [POST]

    Model (application/json)

    {
        "vendor_id": 1,
        "trn_no": 503,
        "particulars": "due",
        "account_details": [
            {
                "id": 1,
                "ledger_id": "104 (Tea)",
                "amount": 500,
                "particulars": "nothing",
                "tax": 200,
                "total": 700
            },
            {
                "id": 2,
                "ledger_id": "105 (Coffee)",
                "amount": 400,
                "particulars": "nothing2",
                "tax": 150,
                "total": 550
            }
        ],
        "trn_date": "2016-11-22",
        "due_date": "2016-11-22",
        "ref": "Account-001",
        "remarks": "pabfb",
        "attachments": [
            {
                "href": "https://example.com/wp-json/wp/v2/media?parent=35"
            }
        ]
    }

+ Response 201 (application/json)
    + Body

            {
                "id": 1,
                "account_no": 503,
                "vendor_id": 1,
                "vendor_name": Apple,
                "trn_no": 503,
                "ledger_id": "104 (Tea)",
                "particulars": "due",
                "account_details": [
                    {
                        "id": 1,
                        "ledger_id": 503,
                        "account_no": 503,
                        "trn_no": 504,
                        "particulars": "nothing",
                        "amount": 80,
                        "tax": 20,
                        "line_total": 100
                    },
                    {
                        "id": 2,
                        "ledger_id": 504,
                        "account_no": 503,
                        "trn_no": 504,
                        "particulars": "nothing",
                        "amount": 90,
                        "tax": 30,
                        "line_total": 120
                    },
                ],
                "date": "2016-11-22",
                "due_date": "2016-11-22",
                "subtotal": 200,
                "total": 200,
                "reference_no": "Account-001",
                "attachments": [
                    {
                        "href": "https://example.com/wp-json/wp/v2/media?parent=35"
                    }
                ],
                "created_by": {
                    "id": 1,
                    "user_nicename": "john",
                    "user_email": "mail@gmail.com",
                    "user_url": "",
                    "display_name": "John Wick",
                    "avatar": "http://2.gravatar.com/avatar/50b8fc98057e12e1f1f8982a981297e7?s=96&d=mm&r=g",
                    "_links": {
                        "self": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                            }
                        ],
                        "collection": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                            }
                        ]
                    }
                },
                "_links": {
                    "self": [
                        {
                            "href": "http://example.com/wp-json/erp/v1/accounting/accounts/1"
                        }
                    ],
                    "collection": [
                        {
                            "href": "http://example.com/wp-json/erp/v1/accounting/accounts"
                        }
                    ]
                },
                "attachments": [
                    {
                        "href": "https://example.com/wp-json/wp/v2/media?parent=35"
                    }
                ]
            }


## Manage Single Account [/accounts/{id}]

+ Parameters
    + id (string) - id of the account in the form of an string

### Retrieve A Account [GET]

+ Response 200 (application/json)
    + Body

            {
                "id": 1,
                "account_no": 503,
                "vendor_id": 1,
                "vendor_name": Apple,
                "trn_no": 503,
                "ledger_id": "104 (Tea)",
                "particulars": "due",
                "account_details": [
                    {
                        "id": 1,
                        "ledger_id": 503,
                        "account_no": 503,
                        "trn_no": 504,
                        "particulars": "nothing",
                        "amount": 80,
                        "tax": 20,
                        "line_total": 100
                    },
                    {
                        "id": 2,
                        "ledger_id": 504,
                        "account_no": 503,
                        "trn_no": 504,
                        "particulars": "nothing",
                        "amount": 90,
                        "tax": 30,
                        "line_total": 120
                    },
                ],
                "date": "2016-11-22",
                "due_date": "2016-11-22",
                "subtotal": 200,
                "total": 200,
                "reference_no": "Account-001",
                "attachments": [
                    {
                        "href": "https://example.com/wp-json/wp/v2/media?parent=35"
                    }
                ],
                "created_by": {
                    "id": 1,
                    "user_nicename": "john",
                    "user_email": "mail@gmail.com",
                    "user_url": "",
                    "display_name": "John Wick",
                    "avatar": "http://2.gravatar.com/avatar/50b8fc98057e12e1f1f8982a981297e7?s=96&d=mm&r=g",
                    "_links": {
                        "self": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                            }
                        ],
                        "collection": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                            }
                        ]
                    }
                },
                "_links": {
                    "self": [
                        {
                            "href": "http://example.com/wp-json/erp/v1/accounting/accounts/1"
                        }
                    ],
                    "collection": [
                        {
                            "href": "http://example.com/wp-json/erp/v1/accounting/accounts"
                        }
                    ],
                }
            }

### Update A Account [PUT]

    Model (application/json)

    {
        "vendor_id": 1,
        "trn_no": 503,
        "particulars": "due",
        "account_details": [
            {
                "id": 1,
                "ledger_id": "104 (Tea)",
                "amount": 500,
                "particulars": "nothing",
                "tax": 200,
                "total": 700
            },
            {
                "id": 2,
                "ledger_id": "105 (Coffee)",
                "amount": 400,
                "particulars": "nothing2",
                "tax": 150,
                "total": 550
            }
        ],
        "trn_date": "2016-11-22",
        "due_date": "2016-11-22",
        "ref": "Account-001",
        "remarks": "pabfb",
        "attachments": [
            {
                "href": "https://example.com/wp-json/wp/v2/media?parent=35"
            }
        ]
    }

+ Response 201 (application/json)
    + Body

            {
                "id": 1,
                "account_no": 503,
                "vendor_id": 1,
                "vendor_name": Apple,
                "trn_no": 503,
                "ledger_id": "104 (Tea)",
                "particulars": "due",
                "account_details": [
                    {
                        "id": 1,
                        "ledger_id": 503,
                        "account_no": 503,
                        "trn_no": 504,
                        "particulars": "nothing",
                        "amount": 80,
                        "tax": 20,
                        "line_total": 100
                    },
                    {
                        "id": 2,
                        "ledger_id": 504,
                        "account_no": 503,
                        "trn_no": 504,
                        "particulars": "nothing",
                        "amount": 90,
                        "tax": 30,
                        "line_total": 120
                    },
                ],
                "date": "2016-11-22",
                "due_date": "2016-11-22",
                "subtotal": 200,
                "total": 200,
                "reference_no": "Account-001",
                "attachments": [
                    {
                        "href": "https://example.com/wp-json/wp/v2/media?parent=35"
                    }
                ],
                "created_by": {
                    "id": 1,
                    "user_nicename": "john",
                    "user_email": "mail@gmail.com",
                    "user_url": "",
                    "display_name": "John Wick",
                    "avatar": "http://2.gravatar.com/avatar/50b8fc98057e12e1f1f8982a981297e7?s=96&d=mm&r=g",
                    "_links": {
                        "self": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                            }
                        ],
                        "collection": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                            }
                        ]
                    }
                },
                "_links": {
                    "self": [
                        {
                            "href": "http://example.com/wp-json/erp/v1/accounting/accounts/1"
                        }
                    ],
                    "collection": [
                        {
                            "href": "http://example.com/wp-json/erp/v1/accounting/accounts"
                        }
                    ]
                }
            }

### Delete A Account [DELETE]

+ Request (application/json)
+ Response 204 (application/json)
