# Group Bills


## Bill List [/bills/{?per_page,page,search,include,type,uid,start,end}]

+ Parameters

    + per_page: 20 (number, optional) - The number of results per page.
        + Default: `20`
    + page: 1 (number, optional) - The current page number of results.
        + Default: `1`
    + search (string, optional) - The search keyword.
    + include: owner (string, optional) - The additional object to be included.
    + type (string, optional) - The type of bill.
    + uid (number, optional) - Filter bills by user id.
    + start (string, optional) - The start date of filtering bills.
    + end (string, optional) - The end date of filtering bills.

### List All Bills [GET]

Fetches all available bills with pagination

+ Response 200 (application/json)
    + Body

            [
                {
                    "id": 1,
                    "bill_no": 503,
                    "vendor_id": 1,
                    "vendor_name": Apple,
                    "transaction_no": 503,
                    "ledger_id": "104 (Tea)",
                    "particulars": "due",
                    "bill_details": [
                        {
                            "id": 1,
                            "bill_no": 503,
                            "transaction_no": 503,
                            "particulars": "nothing",
                            "debit": 0,
                            "credit": 200,
                        },
                        {
                            "id": 2,
                            "bill_no": 503,
                            "transaction_no": 504,
                            "particulars": "nothing",
                            "debit": 150,
                            "credit": 0,
                        }
                    ],
                    "date": "2016-11-22",
                    "due_date": "2016-11-22",
                    "subtotal": 200,
                    "total": 200,
                    "reference_no": "Bill-001",
                    "created_by": {
                        "id": 1,
                        "user_nicename": "john",
                        "user_email": "mail@gmail.com",
                        "user_url": "",
                        "display_name": "John Wick",
                        "avatar": "http://2.gravatar.com/avatar/50b8fc98057e12e1f1f8982a981297e7?s=96&d=mm&r=g",
                        "_links": {
                            "self": [
                                {
                                    "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                                }
                            ],
                            "collection": [
                                {
                                    "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                                }
                            ]
                        }
                    },
                    "_links": {
                        "self": [
                            {
                                "href": "http://example.com/wp-json/erp/v1/accounting/bills/1"
                            }
                        ],
                        "collection": [
                            {
                                "href": "http://example.com/wp-json/erp/v1/accounting/bills"
                            }
                        ]
                    }
                }
            ]

## Bill List [/bills]

### Create A Bill [POST]

    Model (application/json)

    {
        "vendor_id": 1,
        "transaction_no": 503,
        "ledger_id": "104 (Tea)",
        "particulars": "due",
        "bill_details": [
            {
                "id": 1,
                "bill_no": 503,
                "transaction_no": 503,
                "particulars": "nothing",
                "debit": 0,
                "credit": 200,
            },
            {
                "id": 2,
                "bill_no": 503,
                "transaction_no": 504,
                "particulars": "nothing",
                "debit": 150,
                "credit": 0,
            }
        ],
        "date": "2016-11-22",
        "due_date": "2016-11-22",
        "subtotal": 200,
        "total": 200,
        "reference_no": "Bill-001",
        "created_by": 1,
        "attachments": [ "file1.pdf" ],
    }

+ Response 201 (application/json)
    + Body

            {
                "id": 1,
                "bill_no": 503,
                "vendor_id": 1,
                "vendor_name": Apple,
                "transaction_no": 503,
                "ledger_id": "104 (Tea)",
                "particulars": "due",
                "bill_details": [
                    {
                        "id": 1,
                        "bill_no": 503,
                        "transaction_no": 503,
                        "particulars": "nothing",
                        "debit": 0,
                        "credit": 200,
                    },
                    {
                        "id": 2,
                        "bill_no": 503,
                        "transaction_no": 504,
                        "particulars": "nothing",
                        "debit": 150,
                        "credit": 0,
                    }
                ],
                "date": "2016-11-22",
                "due_date": "2016-11-22",
                "subtotal": 200,
                "total": 200,
                "reference_no": "Bill-001",
                "attachments": [
                    {
                        "href": "https://example.com/wp-json/wp/v2/media?parent=35"
                    }
                ],
                "created_by": {
                    "id": 1,
                    "user_nicename": "john",
                    "user_email": "mail@gmail.com",
                    "user_url": "",
                    "display_name": "John Wick",
                    "avatar": "http://2.gravatar.com/avatar/50b8fc98057e12e1f1f8982a981297e7?s=96&d=mm&r=g",
                    "_links": {
                        "self": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                            }
                        ],
                        "collection": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                            }
                        ]
                    }
                },
                "_links": {
                    "self": [
                        {
                            "href": "http://example.com/wp-json/erp/v1/accounting/bills/1"
                        }
                    ],
                    "collection": [
                        {
                            "href": "http://example.com/wp-json/erp/v1/accounting/bills"
                        }
                    ]
                }
            }


## Manage Single Bill [/bills/{id}]

+ Parameters
    + id (string) - id of the bill in the form of an string

### Retrieve A Bill [GET]

+ Response 200 (application/json)
    + Body

            {
                "id": 1,
                "bill_no": 503,
                "vendor_id": 1,
                "vendor_name": Apple,
                "transaction_no": 503,
                "ledger_id": "104 (Tea)",
                "particulars": "due",
                "bill_details": [
                    {
                        "id": 1,
                        "bill_no": 503,
                        "transaction_no": 503,
                        "particulars": "nothing",
                        "debit": 0,
                        "credit": 200,
                    },
                    {
                        "id": 2,
                        "bill_no": 503,
                        "transaction_no": 504,
                        "particulars": "nothing",
                        "debit": 150,
                        "credit": 0,
                    }
                ],
                "date": "2016-11-22",
                "due_date": "2016-11-22",
                "subtotal": 200,
                "total": 200,
                "reference_no": "Bill-001",
                "attachments": [
                    {
                        "href": "https://example.com/wp-json/wp/v2/media?parent=35"
                    }
                ],
                "created_by": {
                    "id": 1,
                    "user_nicename": "john",
                    "user_email": "mail@gmail.com",
                    "user_url": "",
                    "display_name": "John Wick",
                    "avatar": "http://2.gravatar.com/avatar/50b8fc98057e12e1f1f8982a981297e7?s=96&d=mm&r=g",
                    "_links": {
                        "self": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                            }
                        ],
                        "collection": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                            }
                        ]
                    }
                },
                "_links": {
                    "self": [
                        {
                            "href": "http://example.com/wp-json/erp/v1/accounting/bills/1"
                        }
                    ],
                    "collection": [
                        {
                            "href": "http://example.com/wp-json/erp/v1/accounting/bills"
                        }
                    ],
                }
            }

### Update A Bill [PUT]

    Model (application/json)

    {
        "vendor_id": 1,
        "transaction_no": 503,
        "ledger_id": "104 (Tea)",
        "particulars": "due",
        "bill_details": [
            {
                "id": 1,
                "bill_no": 503,
                "transaction_no": 503,
                "particulars": "nothing",
                "debit": 0,
                "credit": 200,
            },
            {
                "id": 2,
                "bill_no": 503,
                "transaction_no": 504,
                "particulars": "updated",
                "debit": 150,
                "credit": 0,
            }
        ],
        "date": "2016-11-22",
        "due_date": "2016-11-22",
        "subtotal": 200,
        "total": 200,
        "reference_no": "Bill-001",
        "created_by": 1
    }

+ Response 201 (application/json)
    + Body

            {
                "id": 1,
                "bill_no": 503,
                "vendor_id": 1,
                "vendor_name": Apple,
                "transaction_no": 503,
                "ledger_id": "104 (Tea)",
                "particulars": "due",
                "bill_details": [
                    {
                        "id": 1,
                        "bill_no": 503,
                        "transaction_no": 503,
                        "particulars": "nothing",
                        "debit": 0,
                        "credit": 200,
                    },
                    {
                        "id": 2,
                        "bill_no": 503,
                        "transaction_no": 504,
                        "particulars": "nothing",
                        "debit": 150,
                        "credit": 0,
                    }
                ],
                "date": "2016-11-22",
                "due_date": "2016-11-22",
                "subtotal": 200,
                "total": 200,
                "reference_no": "Bill-001",
                "attachments": [
                    {
                        "href": "https://example.com/wp-json/wp/v2/media?parent=35"
                    }
                ],
                "created_by": {
                    "id": 1,
                    "user_nicename": "john",
                    "user_email": "mail@gmail.com",
                    "user_url": "",
                    "display_name": "John Wick",
                    "avatar": "http://2.gravatar.com/avatar/50b8fc98057e12e1f1f8982a981297e7?s=96&d=mm&r=g",
                    "_links": {
                        "self": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                            }
                        ],
                        "collection": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                            }
                        ]
                    }
                },
                "_links": {
                    "self": [
                        {
                            "href": "http://example.com/wp-json/erp/v1/accounting/bills/1"
                        }
                    ],
                    "collection": [
                        {
                            "href": "http://example.com/wp-json/erp/v1/accounting/bills"
                        }
                    ]
                }
            }

### Delete A Bill [DELETE]

+ Request (application/json)
+ Response 204 (application/json)


## Make a payment from Bills [/bills/{id}/payment]

### Make a Bill payment [PUT]

    Model (application/json)

    {
        "vendor_id": 1,
        "transaction_no": 503,
        "ledger_id": "104 (Tea)",
        "particulars": "due",
        "bill_details": [
            {
                "id": 1,
                "bill_no": 503,
                "transaction_no": 503,
                "particulars": "nothing",
                "debit": 0,
                "credit": 200,
            },
            {
                "id": 2,
                "bill_no": 503,
                "transaction_no": 504,
                "particulars": "updated",
                "debit": 150,
                "credit": 0,
            }
        ],
        "date": "2016-11-22",
        "due_date": "2016-11-22",
        "subtotal": 200,
        "total": 200,
        "reference_no": "Bill-001",
        "created_by": 1
    }

+ Response 201 (application/json)
    + Body

            {
                "id": 1,
                "bill_no": 503,
                "vendor_id": 1,
                "vendor_name": Apple,
                "transaction_no": 503,
                "ledger_id": "104 (Tea)",
                "particulars": "due",
                "bill_details": [
                    {
                        "id": 1,
                        "bill_no": 503,
                        "transaction_no": 503,
                        "particulars": "nothing",
                        "debit": 0,
                        "credit": 200,
                    },
                    {
                        "id": 2,
                        "bill_no": 503,
                        "transaction_no": 504,
                        "particulars": "nothing",
                        "debit": 150,
                        "credit": 0,
                    }
                ],
                "date": "2016-11-22",
                "due_date": "2016-11-22",
                "subtotal": 200,
                "total": 200,
                "reference_no": "Bill-001",
                "attachments": [
                    {
                        "href": "https://example.com/wp-json/wp/v2/media?parent=35"
                    }
                ],
                "created_by": {
                    "id": 1,
                    "user_nicename": "john",
                    "user_email": "mail@gmail.com",
                    "user_url": "",
                    "display_name": "John Wick",
                    "avatar": "http://2.gravatar.com/avatar/50b8fc98057e12e1f1f8982a981297e7?s=96&d=mm&r=g",
                    "_links": {
                        "self": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                            }
                        ],
                        "collection": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                            }
                        ]
                    }
                },
                "_links": {
                    "self": "http://example.com/wp-json/erp/v1/accounting/bills/1",
                    "collection": "http://example.com/wp-json/erp/v1/accounting/bills"
                }
            }

