# Group Currencies


## Currency List [/currencies]

### List All Currencies [GET]

Fetches all available currencies

+ Response 200 (application/json)
    + Body

            [
                {
                    "id": "1",
                    "name": "AED",
                    "sign": "د.إ",
                    "namespace": "erp/v1",
                    "rest_base": "accounting/v1/currencies",
                    "_links": {
                        "self": {
                            "href": "http://localhost/wperp/wp-json/erp/v1/accounting/v1/currencies/1"
                        },
                        "collection": {
                            "href": "http://localhost/wperp/wp-json/erp/v1/accounting/v1/currencies"
                        }
                    }
                },
                {
                    "id": "2",
                    "name": "AFN",
                    "sign": "؋",
                    "namespace": "erp/v1",
                    "rest_base": "accounting/v1/currencies",
                    "_links": {
                        "self": {
                            "href": "http://localhost/wperp/wp-json/erp/v1/accounting/v1/currencies/2"
                        },
                        "collection": {
                            "href": "http://localhost/wperp/wp-json/erp/v1/accounting/v1/currencies"
                        }
                    }
                }
            ]
