# Group Employees


## Employee List [/employees/{?per_page,page,search}]

+ Parameters

    + per_page: 20 (number, optional) - The number of results per page.
        + Default: `20`
    + page: 1 (number, optional) - The current page number of results.
        + Default: `1`
    + search (string, optional) - The search keyword.


### List All Employees [GET]

Fetches all available employees with pagination

+ Response 200 (application/json)
    + Body

            [
                {
                    "employee_id": "1009",
                    "designation": "Admin",
                    "department": "Administration",
                    "location": "0",
                    "hiring_source": "referral",
                    "hiring_date": "24-10-2019",
                    "termination_date": "0000-00-00",
                    "date_of_birth": "15-02-1999",
                    "reporting_to": 0,
                    "pay_rate": "5000",
                    "pay_type": "monthly",
                    "type": "contract",
                    "status": "active",
                    "end_date": [],
                    "photo_id": 0,
                    "first_name": "Gerson",
                    "middle_name": "",
                    "last_name": "Heidenreich",
                    "other_email": "",
                    "phone": "418.460.7944 x434",
                    "work_phone": "",
                    "blood_group": "",
                    "spouse_name": "",
                    "father_name": "",
                    "mother_name": "",
                    "mobile": "",
                    "address": "269 Alison Trafficway Lake Dantemouth, WI 63430",
                    "gender": "male",
                    "marital_status": "widowed",
                    "nationality": "US",
                    "driving_license": "",
                    "hobbies": "",
                    "user_url": "https://example.com/wp-admin/admin.php?page=erp-hr&section=employee&action=view&id=11",
                    "description": "Hatter was the first figure,' said the Dormouse crossed the court, 'Bring me the list of the cattle in the night? Let me see: I'll give them a new idea to Alice, they all crowded round it, panting.",
                    "street_1": null,
                    "street_2": null,
                    "city": null,
                    "country": null,
                    "state": null,
                    "postal_code": null,
                    "full_name": "Gerson Heidenreich",
                    "namespace": "erp/v1",
                    "rest_base": "accounting/v1/employees",
                    "id": 11,
                    "user_id": 11,
                    "email": "phansen@koch.org",
                    "people_id": "40",
                    "_links": {
                        "self": {
                            "href": "https://example.com/wp-json/erp/v1/accounting/v1/employees/11"
                        },
                        "collection": {
                            "href": "https://example.com/wp-json/erp/v1/accounting/v1/employees"
                        }
                    }
                }
            ]

## Manage Single Employee [/employees/{id}]

+ Parameters
    + id (string) - id of the employee in the form of an string

### Retrieve A Employee [GET]

+ Request (application/json)
+ Response 200 (application/json)
    + Body

            {
                "employee_id": "1009",
                "designation": "Admin",
                "department": "Administration",
                "location": "0",
                "hiring_source": "referral",
                "hiring_date": "24-10-2019",
                "termination_date": "0000-00-00",
                "date_of_birth": "15-02-1999",
                "reporting_to": 0,
                "pay_rate": "5000",
                "pay_type": "monthly",
                "type": "contract",
                "status": "active",
                "end_date": [],
                "photo_id": 0,
                "first_name": "Gerson",
                "middle_name": "",
                "last_name": "Heidenreich",
                "other_email": "",
                "phone": "418.460.7944 x434",
                "work_phone": "",
                "blood_group": "",
                "spouse_name": "",
                "father_name": "",
                "mother_name": "",
                "mobile": "",
                "address": "269 Alison Trafficway Lake Dantemouth, WI 63430",
                "gender": "male",
                "marital_status": "widowed",
                "nationality": "US",
                "driving_license": "",
                "hobbies": "",
                "user_url": "https://example.com/wp-admin/admin.php?page=erp-hr&section=employee&action=view&id=11",
                "description": "Hatter was the first figure,' said the Dormouse crossed the court, 'Bring me the list of the cattle in the night? Let me see: I'll give them a new idea to Alice, they all crowded round it, panting.",
                "street_1": null,
                "street_2": null,
                "city": null,
                "country": null,
                "state": null,
                "postal_code": null,
                "full_name": "Gerson Heidenreich",
                "namespace": "erp/v1",
                "rest_base": "accounting/v1/employees",
                "id": 11,
                "user_id": 11,
                "email": "phansen@koch.org",
                "people_id": "40",
                "_links": {
                    "self": {
                        "href": "https://example.com/wp-json/erp/v1/accounting/v1/employees/11"
                    },
                    "collection": {
                        "href": "https://example.com/wp-json/erp/v1/accounting/v1/employees"
                    }
                }
            }
