# Group Pay Purchase Orders
Group description

## Pay Purchase Order List [/pay_purchase_orders]

### Create A Pay Purchase Order [POST]

    Model (application/json)

        {
            "Line": [{
                "Id": "1",
                "Amount": 25.0,
                "DetailType": "ItemBasedExpenseLineDetail",
                "ItemBasedExpenseLineDetail": {
                    "CustomerRef": {
                        "value": "3",
                        "name": "Cool Cars"
                    },
                    "BillableStatus": "NotBillable",
                    "ItemRef": {
                        "value": "38",
                        "name": "Garden Supplies"
                    },
                    "UnitPrice": 25,
                    "Qty": 1,
                    "TaxCodeRef": {
                        "value": "NON"
                    }
                }
            }],
            "VendorRef": {
                "value": "41",
                "name": "Hicks Hardware"
            },
            "APAccountRef": {
                "value": "33",
                "name": "Accounts Payable (A/P)"
            },
            "TotalAmt": 25.0
        }

+ Response 201 (application/json)
    + Body

            {
                "PurchaseOrder": {
                    "domain": "QBO",
                    "sparse": false,
                    "Id": "259",
                    "SyncToken": "0",
                    "MetaData": {
                        "CreateTime": "2015-07-28T16:06:03-07:00",
                        "LastUpdatedTime": "2015-07-28T16:06:03-07:00"
                    },
                    "CustomField": [{
                        "DefinitionId": "1",
                        "Name": "Crew #",
                        "Type": "StringType"
                    }, {
                        "DefinitionId": "2",
                        "Name": "Sales Rep",
                        "Type": "StringType"
                    }],
                    "DocNumber": "1007",
                    "TxnDate": "2015-07-28",
                    "Line": [{
                        "Id": "1",
                        "Amount": 25.0,
                        "DetailType": "ItemBasedExpenseLineDetail",
                        "ItemBasedExpenseLineDetail": {
                            "CustomerRef": {
                                "value": "3",
                                "name": "Cool Cars"
                            },
                            "BillableStatus": "NotBillable",
                            "ItemRef": {
                                "value": "38",
                                "name": "Garden Supplies"
                            },
                            "UnitPrice": 25,
                            "Qty": 1,
                            "TaxCodeRef": {
                                "value": "NON"
                            }
                        }
                    }],
                    "VendorRef": {
                        "value": "41",
                        "name": "Hicks Hardware"
                    },
                    "APAccountRef": {
                        "value": "33",
                        "name": "Accounts Payable (A/P)"
                    },
                    "TotalAmt": 25.0
                },
                "time": "2015-07-28T16:06:04.864-07:00"
            }

## Manage Single Pay Purchase Order [/pay_purchase_order/{id}]

+ Parameters
	+ id (string) - id of the pay_purchase_order in the form of an string

### Retrieve An Pay Purchase Order [GET]

+ Response 200 (application/json)
	+ Body

			{
                "PurchaseOrder": {
                    "domain": "QBO",
                    "sparse": false,
                    "Id": "259",
                    "SyncToken": "0",
                    "MetaData": {
                        "CreateTime": "2015-07-28T16:06:03-07:00",
                        "LastUpdatedTime": "2015-07-28T16:06:03-07:00"
                    },
                    "CustomField": [{
                        "DefinitionId": "1",
                        "Name": "Crew #",
                        "Type": "StringType"
                    }, {
                        "DefinitionId": "2",
                        "Name": "Sales Rep",
                        "Type": "StringType"
                    }],
                    "DocNumber": "1007",
                    "TxnDate": "2015-07-28",
                    "Line": [{
                        "Id": "1",
                        "Amount": 25.0,
                        "DetailType": "ItemBasedExpenseLineDetail",
                        "ItemBasedExpenseLineDetail": {
                            "CustomerRef": {
                                "value": "3",
                                "name": "Cool Cars"
                            },
                            "BillableStatus": "NotBillable",
                            "ItemRef": {
                                "value": "38",
                                "name": "Garden Supplies"
                            },
                            "UnitPrice": 25,
                            "Qty": 1,
                            "TaxCodeRef": {
                                "value": "NON"
                            }
                        }
                    }],
                    "VendorRef": {
                        "value": "41",
                        "name": "Hicks Hardware"
                    },
                    "APAccountRef": {
                        "value": "33",
                        "name": "Accounts Payable (A/P)"
                    },
                    "TotalAmt": 25.0
                },
                "time": "2015-07-28T16:06:04.864-07:00"
            }

### Update An Pay Purchase Order [PUT]

    Model (application/json)

        {
            "Line": [{
                "Id": "1",
                "Amount": 25.0,
                "DetailType": "ItemBasedExpenseLineDetail",
                "ItemBasedExpenseLineDetail": {
                    "CustomerRef": {
                        "value": "3",
                        "name": "Cool Cars"
                    },
                    "BillableStatus": "NotBillable",
                    "ItemRef": {
                        "value": "38",
                        "name": "Garden Supplies"
                    },
                    "UnitPrice": 25,
                    "Qty": 1,
                    "TaxCodeRef": {
                        "value": "NON"
                    }
                }
            }],
            "VendorRef": {
                "value": "41",
                "name": "Hicks Hardware"
            },
            "APAccountRef": {
                "value": "33",
                "name": "Accounts Payable (A/P)"
            },
            "TotalAmt": 25.0
        }

+ Response 201 (application/json)
    + Body

            {
                "PurchaseOrder": {
                    "VendorAddr": {
                        "Id": "120",
                        "Line1": "Geoff Hicks",
                        "Line2": "Hicks Hardware",
                        "Line3": "42 Main St.",
                        "Line4": "Middlefield, CA  94303"
                    },
                    "ShipAddr": {
                        "Id": "121",
                        "Line1": "Grace Pariente",
                        "Line2": "Cool Cars",
                        "Line3": "65 Ocean Dr.",
                        "Line4": "Half Moon Bay, CA  94213"
                    },
                    "POStatus": "Open",
                    "domain": "QBO",
                    "sparse": false,
                    "Id": "257",
                    "SyncToken": "1",
                    "MetaData": {
                        "CreateTime": "2015-07-28T16:01:47-07:00",
                        "LastUpdatedTime": "2015-07-28T16:17:41-07:00"
                    },
                    "CustomField": [{
                        "DefinitionId": "1",
                        "Name": "Crew #",
                        "Type": "StringType"
                    }, {
                        "DefinitionId": "2",
                        "Name": "Sales Rep",
                        "Type": "StringType"
                    }],
                    "DocNumber": "1005",
                    "TxnDate": "2015-07-28",
                    "CurrencyRef": {
                        "value": "USD",
                        "name": "United States Dollar"
                    },
                    "PrivateNote": "This is a private note added during update.",
                    "Line": [{
                        "Id": "1",
                        "Amount": 25.0,
                        "DetailType": "ItemBasedExpenseLineDetail",
                        "ItemBasedExpenseLineDetail": {
                            "CustomerRef": {
                                "value": "3",
                                "name": "Cool Cars"
                            },
                            "BillableStatus": "NotBillable",
                            "ItemRef": {
                                "value": "38",
                                "name": "Garden Supplies"
                            },
                            "UnitPrice": 25,
                            "Qty": 1,
                            "TaxCodeRef": {
                                "value": "NON"
                            }
                        }
                    }],
                    "VendorRef": {
                        "value": "41",
                        "name": "Hicks Hardware"
                    },
                    "APAccountRef": {
                        "value": "33",
                        "name": "Accounts Payable (A/P)"
                    },
                    "TotalAmt": 25.0
                },
                "time": "2015-07-28T16:17:42.952-07:00"
            }

### Delete An Pay Purchase Order [DELETE]

+ Request (application/json)
+ Response 204 (application/json)
