# Group Payments
Group description

## Payments List [/payments]

### Create A Payment [POST]

    Model (application/json)

        {
            "VendorRef": {
                "value": "56",
                "name": "Bob's Burger Joint"
            },
            "PayType": "Check",
            "CheckPayment": {
                "BankAccountRef": {
                "value": "35",
                "name": "Checking"
                }
            },
            "TotalAmt": 200.00,
            "PrivateNote": "Acct. 1JK90",
            "Line": [
                {
                    "Amount": 200.00,
                    "LinkedTxn": [
                        {
                            "TxnId": "234",
                            "TxnType": "Bill"
                        }
                    ]
                }
            ]
        }

+ Response 201 (application/json)
    + Body

            {
                "BillPayment": {
                    "VendorRef": {
                        "value": "56",
                        "name": "Bob's Burger Joint"
                    },
                    "PayType": "Check",
                    "CheckPayment": {
                        "BankAccountRef": {
                            "value": "35",
                            "name": "Checking"
                        },
                        "PrintStatus": "NeedToPrint"
                    },
                    "TotalAmt": 200.0,
                    "domain": "QBO",
                    "sparse": false,
                    "Id": "236",
                    "SyncToken": "0",
                    "MetaData": {
                        "CreateTime": "2015-07-14T12:34:04-07:00",
                        "LastUpdatedTime": "2015-07-14T12:34:04-07:00"
                    },
                    "TxnDate": "2015-07-14",
                    "PrivateNote": "Acct. 1JK90",
                    "Line": [{
                        "Amount": 200.0,
                        "LinkedTxn": [{
                            "TxnId": "234",
                            "TxnType": "Bill"
                        }]
                    }]
                },
                "time": "2015-07-14T12:34:03.964-07:00"
            }

## Manage Single Payment [/payments/{id}]

+ Parameters
	+ id (string) - id of the payment in the form of an string

### Retrieve An Payment [GET]

+ Response 200 (application/json)
	+ Body

			{
                "BillPayment": {
                    "VendorRef": {
                        "value": "56",
                        "name": "Bob's Burger Joint"
                    },
                    "PayType": "Check",
                    "CheckPayment": {
                        "BankAccountRef": {
                            "value": "35",
                            "name": "Checking"
                        },
                        "PrintStatus": "NeedToPrint"
                    },
                    "TotalAmt": 200.0,
                    "domain": "QBO",
                    "sparse": false,
                    "Id": "236",
                    "SyncToken": "0",
                    "MetaData": {
                        "CreateTime": "2015-07-14T12:34:04-07:00",
                        "LastUpdatedTime": "2015-07-14T12:34:04-07:00"
                    },
                    "TxnDate": "2015-07-14",
                    "PrivateNote": "Acct. 1JK90",
                    "Line": [{
                        "Amount": 200.0,
                        "LinkedTxn": [{
                            "TxnId": "234",
                            "TxnType": "Bill"
                        }]
                    }]
                },
                "time": "2015-07-14T12:34:03.964-07:00"
            }

### Update An Payment [PUT]

    Model (application/json)

        {
            "VendorRef": {
                "value": "56",
                "name": "Bob's Burger Joint"
            },
            "PayType": "Check",
            "CheckPayment": {
                "BankAccountRef": {
                "value": "35",
                "name": "Checking"
                }
            },
            "TotalAmt": 200.00,
            "PrivateNote": "Acct. 1JK90",
            "Line": [
                {
                    "Amount": 200.00,
                    "LinkedTxn": [
                        {
                            "TxnId": "234",
                            "TxnType": "Bill"
                        }
                    ]
                }
            ]
        }

+ Response 201 (application/json)
    + Body

            {
                "BillPayment": {
                    "VendorRef": {
                        "value": "56",
                        "name": "Bob's Burger Joint"
                    },
                    "PayType": "Check",
                    "CheckPayment": {
                        "BankAccountRef": {
                            "value": "35",
                            "name": "Checking"
                        },
                        "PrintStatus": "NeedToPrint"
                    },
                    "TotalAmt": 200.0,
                    "domain": "QBO",
                    "sparse": false,
                    "Id": "236",
                    "SyncToken": "0",
                    "MetaData": {
                        "CreateTime": "2015-07-14T12:34:04-07:00",
                        "LastUpdatedTime": "2015-07-14T12:34:04-07:00"
                    },
                    "TxnDate": "2015-07-14",
                    "PrivateNote": "Acct. 1JK90",
                    "Line": [{
                        "Amount": 200.0,
                        "LinkedTxn": [{
                            "TxnId": "234",
                            "TxnType": "Bill"
                        }]
                    }]
                },
                "time": "2015-07-14T12:34:03.964-07:00"
            }

### Delete An Payment [DELETE]

+ Request (application/json)
+ Response 204 (application/json)
