# Group Product Categories
Group description

## Product Categories List [/product_cats/{?per_page,page,search}]

+ Parameters

	+ per_page: 20 (number, optional) - The number of results per page.
        + Default: `20`
    + page: 1 (number, optional) - The current page number of results.
        + Default: `1`
    + search (string, optional) - The search keyword.

### List All Product Categories [GET]

Fetches all available product_cats with pagination

+ Response 200 (application/json)
    + Body

            [
                {
                    "id": 20,
                    "product_term_name": "Office Products",
                    "description": "office Products Category",
                    "slug": "office_products",
                    "parent": 50,
                    "meta": {},
                    "taxonomy": "product_cat",
                    "product_count": 20,
                    "CreateTime":"2015-10-06T08:50:34-07:00",
                    "LastUpdatedTime":"2015-10-06T08:50:34-07:00",
                    "created_by": {
                        "id": 1,
                        "user_nicename": "john",
                        "user_email": "john@doe.com",
                        "user_url": "http://www.doe.com",
                        "display_name": "John Wick",
                        "avatar": "https://gravatar.com",
                        "_links": {
                            "self": "http://example.com/wp-json/erp/v1/users/1",
                            "collection": "http://example.com/wp-json/erp/v1/users"
                        }
                    },
                    "_links": {
                        "self": "http://example.com/wp-json/erp/v1/accounting/product_cats/20",
                        "collection": "http://example.com/wp-json/erp/v1/accounting/product_cats"
                    }
                }
            ]

## Product Categories List [/product_cats/]

### Create A Product Category [POST]

    Model (application/json)

        {
            "product_cat_name": "Office Products",
            "description": "office Products Category",
            "slug": "office_products",
            "parent": 50,
            "meta": {}
        }

+ Response 201 (application/json)
    + Body

            {
                "id": 20,
                "product_term_name": "Office Products",
                "description": "office Products Category",
                "slug": "office_products",
                "parent": 50,
                "meta": {},
                "taxonomy": "product_cat",
                "product_count": 20,
                "CreateTime":"2015-10-06T08:50:34-07:00",
                "LastUpdatedTime":"2015-10-06T08:50:34-07:00",
                "created_by": {
					"id": 1,
					"user_nicename": "john",
					"user_email": "john@doe.com",
					"user_url": "http://www.doe.com",
					"display_name": "John Wick",
					"avatar": "https://gravatar.com",
					"_links": {
						"self": "http://example.com/wp-json/erp/v1/users/1",
						"collection": "http://example.com/wp-json/erp/v1/users"
					}
				},
                "_links": {
					"self": "http://example.com/wp-json/erp/v1/accounting/product_cats/20",
					"collection": "http://example.com/wp-json/erp/v1/accounting/product_cats"
				}
            }


## Manage Single Product Category [/product_cats/{id}]

+ Parameters
	+ id (string) - id of the product_cat in the form of an string

### Retrieve A Product Category [GET]

+ Response 200 (application/json)
	+ Body

			{
                "id": 20,
                "product_term_name": "Office Products",
                "description": "office Products Category",
                "slug": "office_products",
                "parent": 50,
                "meta": {},
                "taxonomy": "product_cat",
                "product_count": 20,
                "CreateTime":"2015-10-06T08:50:34-07:00",
                "LastUpdatedTime":"2015-10-06T08:50:34-07:00",
                "created_by": {
					"id": 1,
					"user_nicename": "john",
					"user_email": "john@doe.com",
					"user_url": "http://www.doe.com",
					"display_name": "John Wick",
					"avatar": "https://gravatar.com",
					"_links": {
						"self": "http://example.com/wp-json/erp/v1/users/1",
						"collection": "http://example.com/wp-json/erp/v1/users"
					}
				},
                "_links": {
					"self": "http://example.com/wp-json/erp/v1/accounting/product_cats/20",
					"collection": "http://example.com/wp-json/erp/v1/accounting/product_cats"
				}
            }

### Update A Product Category [PUT]

    Model (application/json)

        {
            "product_cat_name": "Office Products",
            "description": "office Products Category",
            "slug": "office_products",
            "parent": 50,
            "meta": {}
        }

+ Response 200 (application/json)
	+ Body

			{
                "id": 20,
                "product_term_name": "Office Products",
                "description": "office Products Category",
                "slug": "office_products",
                "parent": 50,
                "meta": {},
                "taxonomy": "product_cat",
                "product_count": 20,
                "CreateTime":"2015-10-06T08:50:34-07:00",
                "LastUpdatedTime":"2015-10-06T08:50:34-07:00",
                "created_by": {
					"id": 1,
					"user_nicename": "john",
					"user_email": "john@doe.com",
					"user_url": "http://www.doe.com",
					"display_name": "John Wick",
					"avatar": "https://gravatar.com",
					"_links": {
						"self": "http://example.com/wp-json/erp/v1/users/1",
						"collection": "http://example.com/wp-json/erp/v1/users"
					}
				},
                "_links": {
					"self": "http://example.com/wp-json/erp/v1/accounting/product_cats/20",
					"collection": "http://example.com/wp-json/erp/v1/accounting/product_cats"
				}
            }

### Delete A Product Category [DELETE]

+ Request (application/json)
+ Response 204 (application/json)
