# Group Products


## Product List [/products/{?per_page,page,search,include}]

+ Parameters

    + per_page: 20 (number, optional) - The number of results per page.
        + Default: `20`
    + page: 1 (number, optional) - The current page number of results.
        + Default: `1`
    + search (string, optional) - The search keyword.
    + include: owner (string, optional) - The additional object to be included.

### List All Products [GET]

Fetches all available products with pagination

+ Response 200 (application/json)
    + Body

            [
                {
                    "id": 100,
                    "name": "Pen",
                    "description": "Product Description",
                    "sku": Off1324,
                    "cost_price_per_unit": 200.00,
                    "sale_price_per_unit": 300.00,
                    "purchase_account": {
                        "value": "79",
                        "name": "Sales of Product Income"
                    },
                    "tax_info": {
                        "tax_on_sales": 1,
                        "tax_on_purchase": 1,
                    },
                    "type": "product",
                    "cat": [
                        {
                            "category_id": 15
                        }
                    ],
                    "quantity": 10,
                    "images": [
                        {
                          "id": 792,
                          "date_created": "2017-03-23T14:01:13",
                          "date_modified": "2017-03-23T14:01:13",
                          "src": "https://example.com/wp-content/uploads/2017/03/T_2_front-4.jpg",
                        },
                        {
                          "id": 793,
                          "date_created": "2017-03-23T14:01:14",
                          "date_modified": "2017-03-23T14:01:14",
                          "src": "https://example.com/wp-content/uploads/2017/03/T_2_back-2.jpg",
                        }
                    ],
                    "created": "2015-12-09T11:12:39-08:00",
                    "updated": "2015-12-09T11:12:41-08:00",
                    "created_by": {
                        "id": 1,
                        "user_nicename": "john",
                        "user_email": "john@doe.com",
                        "user_url": "http://www.doe.com",
                        "display_name": "John Wick",
                        "avatar": "https://gravatar.com",
                        "_links": {
                            "self": [
                                {
                                    "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                                }
                            ],
                            "collection": [
                                {
                                    "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                                }
                            ]
                        }
                    },
                    "_links": {
                        "self": [
                            {
                                "href": "https://example.com/wp-json/erp/v1/products/794"
                            }
                        ],
                        "collection": [
                            {
                                "href": "https://example.com/wp-json/erp/v1/products"
                            }
                        ]
                    }
                }
            ]

## Product List [/products]

### Create A Product [POST]

    Model (application/json)

    {
        "name": "Pen",
        "description": "Product Description",
        "sku": Off1324,
        "cost_price_per_unit": 200.00,
        "sale_price_per_unit": 300.00,
        "purchase_account": {
            "value": "79",
            "name": "Sales of Product Income"
        },
        "sales_account": {
            "value": "80",
            "name": "Cost of Goods Sold"
        },
        "asset_account": {
            "value": "81",
            "name": "Inventory Asset"
        },
        "tax_info": {
            "tax_on_sales": 1,
            "tax_on_purchase": 1,
        },
        "type": "product",
        "cat": [
            {
                "category_id": 10
            }
        ],
        "quantity": 10
    }

+ Response 201 (application/json)
    + Body

            {
                "id": 100,
                "name": "Pen",
                "description": "Product Description",
                "sku": Off1324,
                "cost_price_per_unit": 200.00,
                "sale_price_per_unit": 300.00,
                "purchase_account": {
                    "value": "79",
                    "name": "Sales of Product Income"
                },
                "tax_info": {
                    "tax_on_sales": 1,
                    "tax_on_purchase": 1,
                },
                "type": "product",
                "cat": [
                    {
                        "category_id": 15
                    }
                ],
                "quantity": 10,
                "images": [
                    {
                      "id": 792,
                      "date_created": "2017-03-23T14:01:13",
                      "date_modified": "2017-03-23T14:01:13",
                      "src": "https://example.com/wp-content/uploads/2017/03/T_2_front-4.jpg",
                    },
                    {
                      "id": 793,
                      "date_created": "2017-03-23T14:01:14",
                      "date_modified": "2017-03-23T14:01:14",
                      "src": "https://example.com/wp-content/uploads/2017/03/T_2_back-2.jpg",
                    }
                ],
                "created": "2015-12-09T11:12:39-08:00",
                "updated": "2015-12-09T11:12:41-08:00",
                "created_by": {
                    "id": 1,
                    "user_nicename": "john",
                    "user_email": "john@doe.com",
                    "user_url": "http://www.doe.com",
                    "display_name": "John Wick",
                    "avatar": "https://gravatar.com",
                    "_links": {
                        "self": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                            }
                        ],
                        "collection": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                            }
                        ]
                    }
                },
                "_links": {
                    "self": [
                        {
                            "href": "https://example.com/wp-json/erp/v1/products/794"
                        }
                    ],
                    "collection": [
                        {
                            "href": "https://example.com/wp-json/erp/v1/products"
                        }
                    ]
                }
            }


## Manage Single Product [/products/{id}]

+ Parameters
    + id (string) - id of the product in the form of an string

### Retrieve A Product [GET]

+ Response 200 (application/json)
    + Body

            {
                "id": 100,
                "name": "Pen",
                "description": "Product Description",
                "sku": Off1324,
                "cost_price_per_unit": 200.00,
                "sale_price_per_unit": 300.00,
                "purchase_account": {
                    "value": "79",
                    "name": "Sales of Product Income"
                },
                "tax_info": {
                    "tax_on_sales": 1,
                    "tax_on_purchase": 1,
                },
                "type": "product",
                "cat": [
                    {
                        "category_id": 15
                    }
                ],
                "quantity": 10,
                "images": [
                    {
                      "id": 792,
                      "date_created": "2017-03-23T14:01:13",
                      "date_modified": "2017-03-23T14:01:13",
                      "src": "https://example.com/wp-content/uploads/2017/03/T_2_front-4.jpg",
                    },
                    {
                      "id": 793,
                      "date_created": "2017-03-23T14:01:14",
                      "date_modified": "2017-03-23T14:01:14",
                      "src": "https://example.com/wp-content/uploads/2017/03/T_2_back-2.jpg",
                    }
                ],
                "created": "2015-12-09T11:12:39-08:00",
                "updated": "2015-12-09T11:12:41-08:00",
                "created_by": {
                    "id": 1,
                    "user_nicename": "john",
                    "user_email": "john@doe.com",
                    "user_url": "http://www.doe.com",
                    "display_name": "John Wick",
                    "_links": {
                        "self": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                            }
                        ],
                        "collection": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                            }
                        ]
                    }
                },
                "_links": {
                    "self": [
                        {
                            "href": "https://example.com/wp-json/erp/v1/products/794"
                        }
                    ],
                    "collection": [
                        {
                            "href": "https://example.com/wp-json/erp/v1/products"
                        }
                    ]
                }
            }

### Update A Product [PUT]

    Model (application/json)

    {
        "name": "Pen Updated",
        "description": "Product Description",
        "sku": Off1324,
        "cost_price_per_unit": 200.00,
        "sale_price_per_unit": 300.00,
        "purchase_account": {
            "value": "79",
            "name": "Sales of Product Income"
        },
        "sales_account": {
            "value": "80",
            "name": "Cost of Goods Sold"
        },
        "asset_account": {
            "value": "81",
            "name": "Inventory Asset"
        },
        "tax_info": {
            "tax_on_sales": 1,
            "tax_on_purchase": 1,
        },
        "type": "product",
        "cat": [
            {
                "category_id": 10
            }
        ],
        "quantity": 10
    }

+ Response 201 (application/json)
    + Body

            {
                "id": 100,
                "name": "Pen",
                "description": "Product Description",
                "sku": Off1324,
                "cost_price_per_unit": 200.00,
                "sale_price_per_unit": 300.00,
                "purchase_account": {
                    "value": "79",
                    "name": "Sales of Product Income"
                },
                "tax_info": {
                    "tax_on_sales": 1,
                    "tax_on_purchase": 1,
                },
                "type": "product",
                "cat": [
                    {
                        "category_id": 15
                    }
                ],
                "quantity": 10,
                "images": [
                    {
                      "id": 792,
                      "date_created": "2017-03-23T14:01:13",
                      "date_modified": "2017-03-23T14:01:13",
                      "src": "https://example.com/wp-content/uploads/2017/03/T_2_front-4.jpg",
                    },
                    {
                      "id": 793,
                      "date_created": "2017-03-23T14:01:14",
                      "date_modified": "2017-03-23T14:01:14",
                      "src": "https://example.com/wp-content/uploads/2017/03/T_2_back-2.jpg",
                    }
                ],
                "created": "2015-12-09T11:12:39-08:00",
                "updated": "2015-12-09T11:12:41-08:00",
                "created_by": {
                    "id": 1,
                    "user_nicename": "john",
                    "user_email": "john@doe.com",
                    "user_url": "http://www.doe.com",
                    "display_name": "John Wick",
                    "avatar": "https://gravatar.com",
                    "_links": {
                        "self": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users/1"
                            }
                        ],
                        "collection": [
                            {
                                "href": "https://demo.wp-api.org/wp-json/wp/v2/users"
                            }
                        ]
                    }
                },
                "_links": {
                    "self": [
                        {
                            "href": "https://example.com/wp-json/erp/v1/products/794"
                        }
                    ],
                    "collection": [
                        {
                            "href": "https://example.com/wp-json/erp/v1/products"
                        }
                    ]
                }
            }

### Delete A Product [DELETE]

+ Request (application/json)
+ Response 204 (application/json)
