# Group Tax Rate Names


## Tax Rate Name List [/tax-zones/{?per_page,page,search,include}]

+ Parameters

    + per_page: 20 (number, optional) - The number of results per page.
        + Default: `20`
    + page: 1 (number, optional) - The current page number of results.
        + Default: `1`
    + search (string, optional) - The search keyword.
    + include: owner (string, optional) - The additional object to be included.

### List All Tax Rate Names [GET]

Fetches all available tax_rates with pagination

+ Response 200 (application/json)
    + Body

            {
                "taxes": [
                    {
                        "id": 1,
                        "name": "Test Tax",
                        "number": "Tax001",
                        "compound": 0,
                        "components" : [
                            {
                                'id' : 1,
                                'component_name': 'VAT',
                                'agency_name': 'NBR',
                                'rate': .15
                            },
                            {
                                'id' : 2,
                                'component_name': 'SD',
                                'agency_name': 'NBR',
                                'rate': .10
                            }
                        ],
                        "created_at": "2016-11-08 03:33:57",
                        "_links": {
                            "self": [
                                {
                                    "href": "www.example.com/wp-json/erp/v1/accounting/taxes/1"
                                }
                            ],
                            "collection": [
                                {
                                    "www.example.com/wp-json/erp/v1/accounting/taxes"
                                }
                            ]
                        }
                    }
                ]
            }

### Create A Tax Rate Name [POST]

    Model (application/json)

    {
        "name": "Test Tax",
        "number": "Tax001",
        "compound": 0,
        "components" : [
            {
                'id' : 1,
                'component_name': 'VAT',
                'agency_name': 'NBR',
                'rate': .15
            },
            {
                'id' : 2,
                'component_name': 'SD',
                'agency_name': 'NBR',
                'rate': .10
            }
        ]
    }

+ Response 201 (application/json)
    + Body

            {
                "id": 1,
                "name": "Test Tax",
                "number": "Tax001",
                "compound": 0,
                "components" : [
                    {
                        'id' : 1,
                        'component_name': 'VAT',
                        'agency_name': 'NBR',
                        'rate': .15
                    },
                    {
                        'id' : 2,
                        'component_name': 'SD',
                        'agency_name': 'NBR',
                        'rate': .10
                    }
                ],
                "created_at": "2016-11-08 03:33:57",
                "_links": {
                    "self": [
                        {
                            "href": "www.example.com/wp-json/erp/v1/accounting/taxes/1"
                        }
                    ],
                    "collection": [
                        {
                            "www.example.com/wp-json/erp/v1/accounting/taxes"
                        }
                    ]
                }
            }


## Manage Single Tax Rate Name [/tax-zones/{id}]

+ Parameters
    + id (string) - id of the tax_rate in the form of an string

### Retrieve A Tax Rate Name [GET]

+ Response 200 (application/json)
    + Body

            {
                "id": 1,
                "name": "Test Tax",
                "number": "Tax001",
                "compound": 0,
                "components" : [
                    {
                        'id' : 1,
                        'component_name': 'VAT',
                        'agency_name': 'NBR',
                        'rate': .15
                    },
                    {
                        'id' : 2,
                        'component_name': 'SD',
                        'agency_name': 'NBR',
                        'rate': .10
                    }
                ],
                "created_at": "2016-11-08 03:33:57",
                "_links": {
                    "self": [
                        {
                            "href": "www.example.com/wp-json/erp/v1/accounting/taxes/1"
                        }
                    ],
                    "collection": [
                        {
                            "www.example.com/wp-json/erp/v1/accounting/taxes"
                        }
                    ]
                }
            }
